const constants = require(`../../../sequelize-constants`);

module.exports = {
    up: queryInterface =>
        queryInterface.bulkInsert(
            constants.TABLES.genres,
            [
                { genre_id: 1, name: 'Adventure|Crime|Drama' },
                { genre_id: 2, name: 'Comedy|Drama' },
                { genre_id: 3, name: 'Drama|Romance' },
                { genre_id: 4, name: 'Comedy' },
                { genre_id: 5, name: 'Animation|Children|Musical' },
                { genre_id: 6, name: 'Comedy|Drama' },
                { genre_id: 7, name: 'Drama|Romance' },
                { genre_id: 8, name: 'Documentary' },
                { genre_id: 9, name: 'Crime|Horror|Mystery|Thriller' },
                { genre_id: 10, name: 'Drama' },
                { genre_id: 11, name: 'Drama|Romance' },
                { genre_id: 12, name: 'Drama' },
                { genre_id: 13, name: 'Drama' },
                { genre_id: 14, name: 'Action|Drama' },
                { genre_id: 15, name: 'Comedy' },
                { genre_id: 16, name: 'Adventure|Drama|Romance|Thriller' },
                { genre_id: 17, name: 'Drama' },
                { genre_id: 18, name: 'Comedy|Drama|Thriller' },
                { genre_id: 19, name: 'Comedy|Horror' },
                { genre_id: 20, name: 'Action|Crime' },
                { genre_id: 21, name: 'Drama|Thriller' },
                { genre_id: 22, name: 'Sci-Fi' },
                { genre_id: 23, name: 'Comedy' },
                { genre_id: 24, name: 'Action|Comedy|Romance|Thriller' },
                { genre_id: 25, name: 'Documentary' },
                { genre_id: 26, name: 'Adventure|Comedy' },
                { genre_id: 27, name: 'Fantasy|Romance|Thriller' },
                { genre_id: 28, name: 'Documentary' },
                { genre_id: 29, name: 'Action|Animation|Children|Comedy|Fantasy' },
                { genre_id: 30, name: 'Comedy' },
                { genre_id: 31, name: 'Comedy|Drama|Romance' },
                { genre_id: 32, name: 'Action|Adventure|Fantasy|Horror' },
                { genre_id: 33, name: 'Comedy' },
                { genre_id: 34, name: 'Drama|Romance|War' },
                { genre_id: 35, name: 'Mystery|Thriller' },
                { genre_id: 36, name: 'Crime|Drama|Thriller' },
                { genre_id: 37, name: 'Documentary|War' },
                { genre_id: 38, name: 'Action|Drama|Thriller' },
                { genre_id: 39, name: 'Drama' },
                { genre_id: 40, name: 'Comedy|Crime' },
                { genre_id: 41, name: 'Drama|Romance' },
                { genre_id: 42, name: 'Drama' },
                { genre_id: 43, name: 'Comedy|Romance' },
                { genre_id: 44, name: 'Documentary' },
                { genre_id: 45, name: 'Sci-Fi' },
                { genre_id: 46, name: 'Animation|Fantasy' },
                { genre_id: 47, name: 'Drama|Romance' },
                { genre_id: 48, name: 'Animation|Drama|Romance' },
                { genre_id: 49, name: 'Comedy' },
                { genre_id: 50, name: 'Comedy|Drama' },
            ],
            {}
        ),

    down: queryInterface => queryInterface.bulkDelete(constants.TABLES.genres, null, {}),
};

